### PR TITLE
Define the Game, Edition, and Card models

### PR DESCRIPTION
**Pull request by jbradberry**
This PR (and PR #3 which has been merged in)

- [x] defines the `Game`, `Edition`, and `Card` models
- [x] exposes each of the models in the Django admin
- [x] provides for useful display of objects of each type, both in the admin and in the shell
- [x] provide a useful tag editing field in the admin for `Card.tags`

### CODE REVIEW

**Comment by jbradberry** [comment]
image

image

**Comment by jbradberry** [comment]
image

**Comment by jbradberry** [comment]
@beeankha I wound up defining explicit `ModelAdmin` classes, so that we can display additional information for each card or edition in the admin list views.  What do you think?

**Review by beeankha — APPROVED** [review]
Looks great!

**Pull request merged**
